package aisafe.aircrafts.domain;

import jakarta.persistence.*;
import lombok.Getter;
import org.springframework.util.Assert;

@Entity
@Getter
public class AircraftModel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String modelName;

    @Column(nullable = false)
    private String manufacturer;
    private Double fuelCapacity;
    private Double maxRange;
    private Double cruisingSpeed;
    @Column(nullable = false)
    private Integer maximumSeatingCapacity;
    private String imagePath;

    public AircraftModel() {

    }

    public AircraftModel(String modelName, String manufacturer, Double fuelCapacity, Double maxRange, Double cruisingSpeed, String imagePath, Integer maximumSeatingCapacity) {
        // doesnt have id because its autogenerated
        Assert.hasText(modelName,"modelName must not be blank");
        Assert.hasText(manufacturer,"manufacturer must not be blank");
        Assert.notNull(fuelCapacity,"fuelCapacity must not be null");
        Assert.notNull(maxRange,"maxRange must not be null");
        Assert.notNull(cruisingSpeed,"cruisingSpeed must not be null");
        // maybe image path can be null, idk if it is really required
        Assert.hasText(imagePath,"imagePath must not be blank");
        Assert.isTrue(maxRange > 0, "maxRange must be greater than zero");
        Assert.isTrue(fuelCapacity > 0, "fuelCapacity must be greater than zero");
        Assert.isTrue(cruisingSpeed > 0, "cruisingSpeed must be greater than zero");
        Assert.isTrue(maximumSeatingCapacity > 0, "maximumSeatingCapacity must be greater than zero");
        this.manufacturer = manufacturer;
        this.modelName = modelName;
        this.fuelCapacity = fuelCapacity;
        this.maxRange = maxRange;
        this.cruisingSpeed = cruisingSpeed;
        this.imagePath = imagePath;
        this.maximumSeatingCapacity = maximumSeatingCapacity;
    }
}
