@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

title System Sequence Diagram - ImportAircraftModelsUseCase

actor "User" as user
participant "System" as sys

user -> sys: import CSV file
activate sys
sys --> user: response (201 Created or 207 Multi-Status)
deactivate sys
@enduml
